// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sibolga_Library.Data;

namespace Sibolga_Library.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.13");

            modelBuilder.Entity("Sibolga_Library.Models.Admin", b =>
                {
                    b.Property<string>("Admin_Id")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("Alamat")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Gambar")
                        .HasColumnType("text");

                    b.Property<string>("Nama_Lengkap")
                        .HasColumnType("text");

                    b.Property<string>("No_Telp")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("RolesId")
                        .HasColumnType("varchar(767)");

                    b.HasKey("Admin_Id");

                    b.HasIndex("RolesId");

                    b.ToTable("Admin");
                });

            modelBuilder.Entity("Sibolga_Library.Models.AksesLogin", b =>
                {
                    b.Property<int>("No")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("RolesId")
                        .HasColumnType("varchar(767)");

                    b.HasKey("No");

                    b.HasIndex("RolesId");

                    b.ToTable("Akses_Login");
                });

            modelBuilder.Entity("Sibolga_Library.Models.Buku", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("Gambar")
                        .HasColumnType("text");

                    b.Property<string>("Judul_Buku")
                        .HasColumnType("text");

                    b.Property<string>("Pemasok_Id")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("Penerbit")
                        .HasColumnType("text");

                    b.Property<string>("Pengarang")
                        .HasColumnType("text");

                    b.Property<string>("Sipnosis")
                        .HasColumnType("text");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Tahun_Terbit")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Pemasok_Id");

                    b.ToTable("Buku");
                });

            modelBuilder.Entity("Sibolga_Library.Models.Detail_Pemasok", b =>
                {
                    b.Property<int>("No")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Jumlah_Poin")
                        .HasColumnType("int");

                    b.Property<string>("Pemasok_Id")
                        .HasColumnType("varchar(767)");

                    b.HasKey("No");

                    b.HasIndex("Pemasok_Id");

                    b.ToTable("Detail_Pemasok");
                });

            modelBuilder.Entity("Sibolga_Library.Models.Pemasok", b =>
                {
                    b.Property<string>("Pemasok_Id")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("Alamat")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Gambar")
                        .HasColumnType("text");

                    b.Property<string>("Nama_Lengkap")
                        .HasColumnType("text");

                    b.Property<string>("No_Telp")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("RolesId")
                        .HasColumnType("varchar(767)");

                    b.HasKey("Pemasok_Id");

                    b.HasIndex("RolesId");

                    b.ToTable("Pemasok");
                });

            modelBuilder.Entity("Sibolga_Library.Models.Pembayaran", b =>
                {
                    b.Property<int>("No")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("PeminjamanId")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<int>("Total_Bayar")
                        .HasColumnType("int");

                    b.HasKey("No");

                    b.HasIndex("PeminjamanId");

                    b.ToTable("Pembayaran");
                });

            modelBuilder.Entity("Sibolga_Library.Models.Peminjaman", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(767)");

                    b.Property<int>("Bayar")
                        .HasColumnType("int");

                    b.Property<string>("Buku_Id")
                        .HasColumnType("varchar(767)");

                    b.Property<DateTime>("Jatuh_Tempo")
                        .HasColumnType("datetime");

                    b.Property<string>("No_Telp")
                        .HasColumnType("text");

                    b.Property<DateTime>("Tgl_Peminjaman")
                        .HasColumnType("datetime");

                    b.Property<string>("User_Id")
                        .HasColumnType("varchar(767)");

                    b.HasKey("Id");

                    b.HasIndex("Buku_Id");

                    b.HasIndex("User_Id");

                    b.ToTable("Peminjaman");
                });

            modelBuilder.Entity("Sibolga_Library.Models.Pengembalian", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(767)");

                    b.Property<int>("Denda")
                        .HasColumnType("int");

                    b.Property<string>("PeminjamanId")
                        .HasColumnType("varchar(767)");

                    b.Property<DateTime>("Tgl_Pengembalian")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("PeminjamanId");

                    b.ToTable("Pengembalian");
                });

            modelBuilder.Entity("Sibolga_Library.Models.Riwayat_Penarikan", b =>
                {
                    b.Property<int>("No")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Jumlah_Poin")
                        .HasColumnType("int");

                    b.Property<string>("Pemasok_Id")
                        .HasColumnType("varchar(767)");

                    b.Property<DateTime>("Tgl_Penarikan")
                        .HasColumnType("datetime");

                    b.HasKey("No");

                    b.HasIndex("Pemasok_Id");

                    b.ToTable("Riwayat_Penarikan");
                });

            modelBuilder.Entity("Sibolga_Library.Models.Roles", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = "2",
                            Name = "Pemasok"
                        },
                        new
                        {
                            Id = "3",
                            Name = "User"
                        });
                });

            modelBuilder.Entity("Sibolga_Library.Models.User", b =>
                {
                    b.Property<string>("User_Id")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("Alamat")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Gambar")
                        .HasColumnType("text");

                    b.Property<string>("Nama_Lengkap")
                        .HasColumnType("text");

                    b.Property<string>("No_Telp")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("RolesId")
                        .HasColumnType("varchar(767)");

                    b.HasKey("User_Id");

                    b.HasIndex("RolesId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Sibolga_Library.Models.Admin", b =>
                {
                    b.HasOne("Sibolga_Library.Models.Roles", "FkRoles")
                        .WithMany()
                        .HasForeignKey("RolesId");

                    b.Navigation("FkRoles");
                });

            modelBuilder.Entity("Sibolga_Library.Models.AksesLogin", b =>
                {
                    b.HasOne("Sibolga_Library.Models.Roles", "Roles")
                        .WithMany()
                        .HasForeignKey("RolesId");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("Sibolga_Library.Models.Buku", b =>
                {
                    b.HasOne("Sibolga_Library.Models.Pemasok", "FkPemasokId")
                        .WithMany()
                        .HasForeignKey("Pemasok_Id");

                    b.Navigation("FkPemasokId");
                });

            modelBuilder.Entity("Sibolga_Library.Models.Detail_Pemasok", b =>
                {
                    b.HasOne("Sibolga_Library.Models.Pemasok", "FkPemasokId")
                        .WithMany()
                        .HasForeignKey("Pemasok_Id");

                    b.Navigation("FkPemasokId");
                });

            modelBuilder.Entity("Sibolga_Library.Models.Pemasok", b =>
                {
                    b.HasOne("Sibolga_Library.Models.Roles", "FkRoles")
                        .WithMany()
                        .HasForeignKey("RolesId");

                    b.Navigation("FkRoles");
                });

            modelBuilder.Entity("Sibolga_Library.Models.Pembayaran", b =>
                {
                    b.HasOne("Sibolga_Library.Models.Peminjaman", "FkPeminjaman")
                        .WithMany()
                        .HasForeignKey("PeminjamanId");

                    b.Navigation("FkPeminjaman");
                });

            modelBuilder.Entity("Sibolga_Library.Models.Peminjaman", b =>
                {
                    b.HasOne("Sibolga_Library.Models.Buku", "FkBukuId")
                        .WithMany()
                        .HasForeignKey("Buku_Id");

                    b.HasOne("Sibolga_Library.Models.User", "FkUserId")
                        .WithMany()
                        .HasForeignKey("User_Id");

                    b.Navigation("FkBukuId");

                    b.Navigation("FkUserId");
                });

            modelBuilder.Entity("Sibolga_Library.Models.Pengembalian", b =>
                {
                    b.HasOne("Sibolga_Library.Models.Peminjaman", "FkPeminjaman")
                        .WithMany()
                        .HasForeignKey("PeminjamanId");

                    b.Navigation("FkPeminjaman");
                });

            modelBuilder.Entity("Sibolga_Library.Models.Riwayat_Penarikan", b =>
                {
                    b.HasOne("Sibolga_Library.Models.Pemasok", "FkPemasokId")
                        .WithMany()
                        .HasForeignKey("Pemasok_Id");

                    b.Navigation("FkPemasokId");
                });

            modelBuilder.Entity("Sibolga_Library.Models.User", b =>
                {
                    b.HasOne("Sibolga_Library.Models.Roles", "FkRoles")
                        .WithMany()
                        .HasForeignKey("RolesId");

                    b.Navigation("FkRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
